### ISSUE TITLE
Adding comments to the hosts file

### ISSUE THREAD

**Issue by tuxiqae** [JannikHv/hstctl#1]
Hi, Hstcl looks really cool, the only downside I can see, is not having comments support.
Would it be possible for you to add that feature?

**Comment by JannikHv** [comment]
This is a great idea! This'll definitely be the next feature I'm going to implement.

An entry would then (plain text) look something like:

`192.168.1.1 example.com # Some note`

Not quite sure how to properly display the note/comment when listing entries but we'll find a way. If you have some ideas/preferences definitely let me know.

I'm going to leave this issue open and start working on this feature in about two days.

Cheers!

**Comment by JannikHv** [comment]
The basic implementation of the feature can now be tested on its feature branch:

https://github.com/JannikHv/hstctl/tree/feature/Comments

**Comment by JannikHv** [comment]
Feature has been merged into master:

https://github.com/JannikHv/hstctl/commit/a8e7baed2a3ea617f83d29618bb36321e02d1a98

**Comment by tuxiqae** [comment]
Thanks mate! I will test it later
